### ISSUE TITLE
云存储和支持API，在App SDK开发的app上本地植入后有如下报错。

### ISSUE THREAD

**Issue by ZYFxy7816** [TuyaInc/tuyasmart_camera_android_sdk#21] opened 2020-03-19 08:19 UTC
we tried to integrate the Cloud Storage/payment api with IPC.
however the build failed with:
FAILURE: Build failed with an exception.

What went wrong:
Circular dependency between the following tasks:
:app:compileKodakDebugJavaWithJavac
+--- :app:generateKodakDebugSources
| --- :app:processKodakDebugResources
| +--- :app:mergeKodakDebugResources
| | --- :app:fabricGenerateResourcesKodakDebug
| | --- :app:mergeKodakDebugAssets
| | --- :app:compileKodakDebugJavaWithJavac ()
| --- :app:splitsDiscoveryTaskKodakDebug
| --- :app:mergeKodakDebugResources ()
--- :app:processKodakDebugResources (*)
(*) - details omitted (listed previously)

This happened after we added :
apply plugin: 'tymodule-config'

...
// tuya camera module
implementation 'com.tuya.smart:tuyasmart-ipc-camera-middleware:3.13.1r129-SNAPSHOT'
implementation 'com.tuya.smart:tuyasmart-ipc-devicecontrol:3.13.1r129-SNAPSHOT'

//商城组件
implementation 'com.tuya.smart:tuyasmart-webcontainer:3.12.6r125'
implementation 'com.tuya.smart:tuyasmart-xplatformmanager:1.1.0'
implementation "com.tuya.smart:tuyasmart-base:3.13.0r127"
implementation 'com.tuya.smart:tuyasmart-appshell:3.10.0'
implementation "com.tuya.smart:tuyasmart-stencilwrapper:3.13.0r127"
implementation "com.tuya.smart:tuyasmart-framework:3.13.0r127-open-rc.1"
implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.3'

**Comment by TuyaRockSugar** [comment] 2020-03-19 08:29
您好，贴一下模块下详细的build.gradle文件，找到循环依赖的组件排除

**Comment by ZYFxy7816** [comment] 2020-03-19 08:42
@Phung: please input detail build.gradle file,  and find/ exclude Circular dependency module

**Comment by THANHMAP** [comment] 2020-03-26 08:41
> @phung: please input detail build.gradle file, and find/ exclude Circular dependency module
if add apply plugin: 'tymodule-config' in build.gradle the build failed with:
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:compileKodakDebugJavaWithJavac
+--- :app:generateKodakDebugSources
|    \--- :app:processKodakDebugResources
|         +--- :app:mergeKodakDebugResources
|         |    \--- :app:fabricGenerateResourcesKodakDebug
|         |         \--- :app:mergeKodakDebugAssets
|         |              \--- :app:compileKodakDebugJavaWithJavac (*)
|         \--- :app:splitsDiscoveryTaskKodakDebug
|              \--- :app:mergeKodakDebugResources (*)
\--- :app:processKodakDebugResources (*)

**Comment by TuyaRockSugar** [comment] 2020-03-27 12:06
please upload the  plugin 'tymodule-config': 'com.tuya.android.module:tymodule-config:0.5.1',
and add 'closeJDM= true' in the gradle.properties

**Comment by THANHMAP** [comment] 2020-04-01 07:43
> please update the plugin 'tymodule-config': 'com.tuya.android.module:tymodule-config:0.5.1',
> and add 'closeJDM= true' in the gradle.properties

Hi, Thank you for the reply. I have corrected the information as you instructed, It was no more error "Circular dependency", but I get a new error when the build is "Program type already present: com.a.a.a.a"

Please help with this case

**Comment by Tuya-DJ** [comment] 2020-04-02 02:07
How to arrange alias configuration in the corresponding proguard-rules.pro file？

**Comment by THANHMAP** [comment] 2020-04-03 01:57
I arrange the alias configuration in proguard-rules.pro file according to the doc instructions

#fastJson
-keep class com.alibaba.fastjson.**{*;}
-dontwarn com.alibaba.fastjson.**

#mqtt
-keep class org.eclipse.paho.client.mqttv3.** { *; }
-dontwarn org.eclipse.paho.client.mqttv3.**

#tutk
-keep class com.tutk.**{*;}
-dontwarn com.tutk.**

-keep class com.squareup.okhttp.** { *; }
-keep interface com.squareup.okhttp.** { *; }
-dontwarn com.squareup.okhttp.**

-keep class okio.** { *; }
-dontwarn okio.**

-keep class com.tuya.**{*;}
-dontwarn com.tuya.**
-keep class com.tuyasmart.**{*;}
-dontwarn com.tuyasmart.**

[https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/en/](url)

**Comment by TuyaRockSugar** [comment] 2020-04-09 08:52
please Reference document：https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/en/resource/Integrated.html

**Comment by THANHMAP** [comment] 2020-04-10 02:43
This is the following error when I refer to the document:[https://tuyainc.github.io/tuyasmart_camera_android_sdk_doc/en/resource/Integrated.html](url)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeKodakDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: duplicate value for resource 'attr/text' with config ''.
  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: resource previously defined here.
  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:7322: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
  
  Command: C:\Users\PremieLink\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ba0636a87c0814a46ad58e09c382e011\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Work\feature_mp4_android\app\build\intermediates\res\merged\kodak\debug \
          C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Work\feature_mp4_android\app\src\main\res\values\attrs.xml:240:5-247:25: AAPT: error: duplicate value for resource 'attr/text' with config ''.
      
  C:\Work\feature_mp4_android\app\src\main\res\values\attrs.xml:240:5-247:25: AAPT: error: resource previously defined here.
      
  C:\Work\feature_mp4_android\app\src\main\res\values\strings.xml:1151:5-245: AAPT: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.

![image](https://user-images.githubusercontent.com/10345001/78957301-31e46900-7b0f-11ea-918b-f7779e391a09.png)

this is file gradle.buid and file .pro of app
[proguard.txt](https://github.com/TuyaInc/tuyasmart_camera_android_sdk/files/4459638/proguard.txt)
[gradle.txt](https://github.com/TuyaInc/tuyasmart_camera_android_sdk/files/4459639/gradle.txt)

**Comment by TuyaRockSugar** [comment] 2020-04-15 07:03
implementation "com.tuya.smart:tuyaCamera:3.11.0r119h2" is not needed，delete it

**Comment by THANHMAP** [comment] 2020-04-15 07:40
> implementation "com.tuya.smart:tuyaCamera:3.11.0r119h2" is not needed，delete it


I tried deleting the API "com.tuya.smart:tuyaCamera:3.11.0r119h2" as you instructed but the error was the same

![image](https://user-images.githubusercontent.com/10345001/79310990-fab6f300-7f26-11ea-9c51-611182526ce1.png)

**Comment by TuyaRockSugar** [comment] 2020-04-15 09:11
Do you define the 'attrs/text' attribute under attrs? if not ,try to add it

**Comment by THANHMAP** [comment] 2020-04-15 09:49
> Do you define the 'attrs/text' attribute under attrs? if not ,try to add it

I defined the attribute 'attrs / text' according to attrs and the error it reported was "AAPT: error: duplicate value for resource 'attr/text' with config '", and this error after when I build again

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeKodakDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  Output:  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: duplicate value for resource 'attr/text' with config ''.
  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: resource previously defined here.
  
  Command: C:\Users\PremieLink\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ba0636a87c0814a46ad58e09c382e011\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Work\feature_mp4_android\app\build\intermediates\res\merged\kodak\debug \
          C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
  Output:  C:\Users\PremieLink\.gradle\caches\transforms-1\files-1.1\tuyasmart-uispecs-0.0.3.aar\39836a47913ddc0a3b02a41e18eea410\res\values\values.xml:110:5-122:296: AAPT: error: duplicate value for resource 'attr/text' with config ''.
      
  C:\Users\PremieLink\.gradle\caches\transforms-1\files-1.1\tuyasmart-uispecs-0.0.3.aar\39836a47913ddc0a3b02a41e18eea410\res\values\values.xml:110:5-122:296: AAPT: error: resource previously defined here.
      
  Command: C:\Users\PremieLink\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ba0636a87c0814a46ad58e09c382e011\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy \
          -o \
          C:\Work\feature_mp4_android\app\build\intermediates\res\merged\kodak\debug \
          C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

![image](https://user-images.githubusercontent.com/10345001/79323955-162af980-7f39-11ea-97ab-6c4eca91f87f.png)

**Comment by TuyaRockSugar** [comment] 2020-04-24 02:29
Thank you for your feedback. We will update the SDK after the problem is solved

**Comment by TuyaRockSugar** [comment] 2020-05-19 11:35
> > Do you define the 'attrs/text' attribute under attrs? if not ,try to add it
> 
> I defined the attribute 'attrs / text' according to attrs and the error it reported was "AAPT: error: duplicate value for resource 'attr/text' with config '", and this error after when I build again
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:mergeKodakDebugResources'.
> 
> > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
> > Output:  C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: duplicate value for resource 'attr/text' with config ''.
> > C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml:4656: error: resource previously defined here.
> 
> Command: C:\Users\PremieLink.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ba0636a87c0814a46ad58e09c382e011\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy
> -o
> C:\Work\feature_mp4_android\app\build\intermediates\res\merged\kodak\debug
> C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml
> Daemon: AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> Output: C:\Users\PremieLink.gradle\caches\transforms-1\files-1.1\tuyasmart-uispecs-0.0.3.aar\39836a47913ddc0a3b02a41e18eea410\res\values\values.xml:110:5-122:296: AAPT: error: duplicate value for resource 'attr/text' with config ''.
> 
> C:\Users\PremieLink.gradle\caches\transforms-1\files-1.1\tuyasmart-uispecs-0.0.3.aar\39836a47913ddc0a3b02a41e18eea410\res\values\values.xml:110:5-122:296: AAPT: error: resource previously defined here.
> 
> Command: C:\Users\PremieLink.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\ba0636a87c0814a46ad58e09c382e011\aapt2-3.2.1-4818971-windows\aapt2.exe compile --legacy
> -o
> C:\Work\feature_mp4_android\app\build\intermediates\res\merged\kodak\debug
> C:\Work\feature_mp4_android\app\build\intermediates\incremental\mergeKodakDebugResources\merged.dir\values\values.xml
> Daemon: AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
> 
> ![image](https://user-images.githubusercontent.com/10345001/79323955-162af980-7f39-11ea-97ab-6c4eca91f87f.png)
hi，you need to upgrade the homeSdk, try to implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.5'

**Comment by THANHMAP** [comment] 2020-05-20 02:35
I have updated to the latest SDK.

    implementation 'com.alibaba:fastjson:1.1.67.android'
    implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.12.3'
    // required tuya home sdk
    implementation 'com.tuya.smart:tuyasmart:3.17.0-beta1'

    // tuya camera module
    implementation 'com.tuya.smart:tuyasmart-ipc-camera-middleware:3.14.3r133'
    implementation 'com.tuya.smart:tuyasmart-ipc-camera-v2:3.17.0r139'
    implementation 'com.tuya.smart:tuyasmart-ipc-camera-utils:3.13.0r129h1'
    implementation 'com.tuya.smart:tuyasmart-ipc-camera-message:3.13.0r128'
    implementation 'com.tuya.smart:tuyasmart-ipc-devicecontrol:3.17.0r139'
    //messge center imagepipeline
    implementation 'com.tuya.smart:tuyasmart-imagepipeline-okhttp3:0.0.1'
    implementation 'com.facebook.fresco:fresco:1.3.0'

    //Mall components
    implementation 'com.tuya.smart:tuyasmart-webcontainer:3.17.6r141-open'
    implementation 'com.tuya.smart:tuyasmart-xplatformmanager:1.1.0'
    implementation "com.tuya.smart:tuyasmart-base:3.17.0r139-rc.3"
    implementation 'com.tuya.smart:tuyasmart-appshell:3.10.0'
    implementation "com.tuya.smart:tuyasmart-stencilwrapper:3.17.0.2r139"
    implementation "com.tuya.smart:tuyasmart-framework:3.17.0.2r139-external"
    implementation 'com.tuya.smart:tuyasmart-uispecs:0.0.5'

If add classpath 'com.tuya.android.module:tymodule-config:0.4.0-SNAPSHOT' in  root build.gradle file then the build fails
FAILURE: Build failed with an exception.

* What went wrong:
Circular dependency between the following tasks:
:app:compileKodakDebugJavaWithJavac
+--- :app:generateKodakDebugSources
|    \--- :app:processKodakDebugResources
|         +--- :app:mergeKodakDebugResources
|         |    \--- :app:fabricGenerateResourcesKodakDebug
|         |         \--- :app:mergeKodakDebugAssets
|         |              \--- :app:compileKodakDebugJavaWithJavac (*)
|         \--- :app:splitsDiscoveryTaskKodakDebug
|              \--- :app:mergeKodakDebugResources (*)
\--- :app:processKodakDebugResources (*)

(*) - details omitted (listed previously)

![image](https://user-images.githubusercontent.com/10345001/82398165-5b80a080-9a7c-11ea-9aff-baee48b46f9b.png)


If add classpath 'classpath 'com.tuya.android.module:tymodule-config:0.5.1'' in  root build.gradle file then the build fails

Program type already present: com.a.a.a.a

![image](https://user-images.githubusercontent.com/10345001/82398347-e06bba00-9a7c-11ea-9090-c3acc9bce281.png)


Please help with this case

**Comment by TuyaRockSugar** [comment] 2020-05-21 02:30
y , clean the project and try again

**Comment by THANHMAP** [comment] 2020-05-21 03:13
> y , clean the project and try again

I tried again and still get the same error

**Comment by TuyaRockSugar** [comment] 2020-05-21 07:09
Please locate com.a.a.a.a under which module？ It seems that there's something wrong with proguard.txt

**Comment by THANHMAP** [comment] 2020-05-26 08:51
After I cleaned and rebuilt the project was Ok, Thanks
But When I use api cameraCloudSDK.buyCloudStorage(CameraCloudStorageActivity.this,
                                   TuyaHomeSdk.getDataInstance().getDeviceBean(devId),
                                   String.valueOf(FamilyManager.getInstance().getCurrentHomeId()), new ICloudManagerCallback() {
                                     @Override
                                     public void onError(int i) {

                                     }

                                     @Override
                                     public void onSuccess(Object o) {
                                       String uri = (String) o;
                                       Intent intent = new Intent(CameraCloudStorageActivity.this, WebViewActivity.class);
                                       intent.putExtra("Uri",uri);
                                       startActivity(intent);
                                     }
                                   });
app crashed with error:

E/UncaughtException: java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/functions/Consumer;
        at com.tuya.smart.camera.middleware.cloud.b.a(Unknown Source:0)
        at com.tuya.smart.camera.middleware.cloud.CameraCloudSDK.buyCloudStorage(Unknown Source:0)

**Comment by yazhidev** [comment] 2020-06-05 10:04
add dependencies:

```
implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
implementation 'io.reactivex.rxjava2:rxjava:2.2.9'
```

**Comment by THANHMAP** [comment] 2020-06-10 08:29
Thanks for the tutorial. I used the api buyCloudStorage. But when the api response succeeds with WebViewActivity is the error
java.lang.RuntimeException: java.io.FileNotFoundException: module_app.json

**Comment by yazhidev** [comment] 2020-06-10 08:38
add dependency in build.gradle under the project directory: 

```
classpath 'com.tuya.android.module:tymodule-config:0.4.0-SNAPSHOT'
```

then, apply plugin in build.gradle under the app directory:

```
apply plugin: 'tymodule-config'
```

**Comment by THANHMAP** [comment] 2020-06-10 08:42
yeah, i'm following the docs guide and I'm using api
classpath 'com.tuya.android.module:tymodule-config:0.5.1'

**Comment by yazhidev** [comment] 2020-06-10 08:54
have you applied plugin 'tymodule-config' ? if there are still problems, can you show your build.gradle of project directory and app directory？

**Comment by THANHMAP** [comment] 2020-06-10 08:58
These are two build.gradle files

[build_app.txt](https://github.com/TuyaInc/tuyasmart_camera_android_sdk/files/4757295/build_app.txt)
[build_project.txt](https://github.com/TuyaInc/tuyasmart_camera_android_sdk/files/4757296/build_project.txt)

**Comment by yazhidev** [comment] 2020-06-10 09:37
apply plugin in build.gradle under the app directory:

```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

apply plugin: 'tymodule-config' //add this

android {
    compileSdkVersion 28

    flavorDimensions "brand"

...

```

**Comment by THANHMAP** [comment] 2020-06-10 10:21
Thank you for supporting it work

**Closed** 2020-08-10 07:02 UTC
